title: "Ben Elliot's Portfolio"
email: "your-email@example.com"
description: "Showcasing the projects of Ben Elliot, a passionate developer focused on creating impactful software solutions."
baseurl: "" # Leave as is unless you have a subpath
url: "https://ben-elliot27.github.io" # Update with your actual GitHub Pages URL
twitter_username: "BenElliot27"
github_username: "Ben-elliot27"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Collections (for projects)
collections:
  projects:
    output: true
