# Site settings
email: "your-email@example.com"
description: "Showcasing the projects of Ben Elliot, a passionate developer focused on creating impactful software solutions."
baseurl: ""
url: "https://ben-elliot27.github.io"
twitter_username: "BenElliot27"
github_username: "Ben-elliot27"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-footnotes
  - jekyll-include-cache

paginate: 5
paginate_path: "/page/:num/"

# Navigation setup
header:
  title: "Ben Elliot’s Portfolio"
  nav:
    - text: "Home"
      url: "/"
    - text: "Projects"
      url: "/projects/"
    - text: "Blog"
      url: "/blog/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
    layout: single

# Footer links
footer_links:
  - title: "GitHub"
    url: "https://github.com/Ben-elliot27"
  - title: "Email"
    url: "mailto:your-email@example.com"

# Minimal Mistakes specific settings
author_profile: true
show_downloads: true
toc: true

# UI Color
color_scheme: "dark"

# Logo and styling
# logo:
#   - image: https://github.githubassets.com/images/icons/emoji/octocat.png
#     alt: "GitHub Octocat"

# Syntax highlighting
highlighter: rouge
syntax_theme: https://cdn.jsdelivr.net/gh/stygiansaby/rouge-themes/css/monokai.css

# Buttons and links
buttons:
  zip_url: https://github.com/mmistakes/minimal-mistakes
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true
