# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Ben Elliot's Portfolio"
email: "benjelliot@outlook.com"
description: "Showcasing the projects of Ben Elliot, a passionate developer focused on creating impactful software solutions."
baseurl: "" # Leave as is unless you have a subpath
url: "https://ben-elliot27.github.io" # Update with your actual GitHub Pages URL
twitter_username: "" # Update if you have a Twitter account
github_username: "Ben-elliot27" # Your GitHub username
# SEO settings
lang: "en"


# Build settings
theme: jekyll-theme-cayman-blog
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5 # Number of projects/posts per page
paginate_path: "/page/:num/"


# Navigation links
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

# Footer links (if supported by theme)
footer_links:
  - title: "GitHub"
    url: "https://github.com/Ben-elliot27"
  - title: "LinkedIn"
    url: "https://linkedin.com/in/ben-elliot"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
