# Theme Settings
minimal_mistakes_skin: "default" # Skins: "air", "aqua", "contrast", etc.
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Site Settings
locale: "en-US"
title: "Ben Elliot's Portfolio"
title_separator: "-"
subtitle: "Showcasing My Work and Projects"
name: "Ben Elliot"
description: "An amazing portfolio showcasing my work."
url: "https://ben-elliot27.github.io"
baseurl: ""
repository: "Ben-elliot27/Ben-elliot27.github.io"
logo: "/assets/images/logo.png"
masthead_title: " "
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
copyright: "Ben Elliot"
copyright_url: "https://ben-elliot27.github.io"
comments:
  provider: false # Enable if needed

# Social Sharing
social:
  type: "Person"
  name: "Ben Elliot"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Ben-elliot27"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "YOUR_TRACKING_ID"

# Site Author
author:
  name: "Ben Elliot"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "A passionate developer."
  location: "Somewhere, Earth"
  email: "your-email@example.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your-email@example.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/your-profile"

# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Ben-elliot27"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/your-profile"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - node_modules
  - Gemfile
  - package.json
  - tmp
  - .sass-cache
  - .jekyll-cache
  - .jekyll-assets-cache

keep_files:
  - .git

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: "America/New_York"

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development


collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
