title: "Ben Elliot's Portfolio"
email: "your-email@example.com"
description: "Showcasing the projects of Ben Elliot, a passionate developer focused on creating impactful software solutions."
baseurl: "" # Leave as is unless you have a subpath
url: "https://ben-elliot27.github.io" # Update with your actual GitHub Pages URL
twitter_username: "BenElliot27"
github_username: "Ben-elliot27"

remote_theme: tuur29/cayman@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Collections (for projects)
collections:
  projects:
    output: true


footer_links:
  - title: "GitHub"
  - url: "https://github.com/Ben-elliot27"
  - email: "your-email@example.com"
  - github_username: "Ben-elliot27"


show_downloads: true
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/tuur29/pages-themes-cayman
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true
